### ISSUE TITLE
Still not launching...

### ISSUE THREAD

**Issue by Holraven** [leafi/fix-spacechem-os-x#1]
I've tried both by script and manually downloading SDL Image 1.2.10 (and also the newer 2.0.4). I've tried with both Mono 4.2.2.30 (SR1) 32-bit and Universal Preview (32+64 bit).

Same results every time: Steam launches the Zachtronics website, and running manually through terminal results in a FileNotFoundExtension.

```
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'SpaceChem.exe' or one of its dependencies
File name: 'SpaceChem.exe'
  at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssembly (string,System.Security.Policy.Evidence,string[])
  at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssembly (string,System.Security.Policy.Evidence,string[])
  at #=qrEwbiPMszIEB9Azc_qhPwVFBd_U1GAjarN4Be6khTX0=.#=q6SCD5KBoFBNiZtK8BfDrdQ== (System.String[] #=q7uUkEPDZNgVk4qYJrF82EQ==) <0x703ed8 + 0x000e7> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'SpaceChem.exe' or one of its dependencies
File name: 'SpaceChem.exe'
  at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssembly (string,System.Security.Policy.Evidence,string[])
  at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssembly (string,System.Security.Policy.Evidence,string[])
  at #=qrEwbiPMszIEB9Azc_qhPwVFBd_U1GAjarN4Be6khTX0=.#=q6SCD5KBoFBNiZtK8BfDrdQ== (System.String[] #=q7uUkEPDZNgVk4qYJrF82EQ==) <0x703ed8 + 0x000e7> in <filename unknown>:0
```

**Comment by leafi** [comment]
Be aware that SDL 1.2 and SDL2 have different APIs and are effectively considered different libraries. SpaceChem is a SDL 1.2 only application. It isn't aware of SDL2.

Would you be willing to run the script again, and copy and paste the output from the Terminal window here? It provides some diagnostic information about which Mono installed where and what architecture they are.

With regards to the FileNotFoundException: This is actually pretty odd. If you think you might have accidentally deleted something important, consider going to your Steam Library (in actual Steam), right-clicking SpaceChem, click Properties, then go Local Files -> Verify Integrity of Game Cache... to restore all files to the state in which they were shipped then running the script again (and paste the output of the script here!).

Otherwise, we can try to get some more information out of mono as follows:

Assuming you were doing `cd (the right directory)` .. `mono SpaceChem.exe` please do the following and copy and paste all the Terminal output:

`cd (the right directory)`

`mono --version`

(^ paying attention to what Architecture: says)

`/Library/Frameworks/Mono.framework/Commands/mono --version`

`which mono`

`pwd`

`MONO_LOG_LEVEL=debug mono SpaceChem.exe`

(replacing 'mono' above if necessary.  The MONO_LOG_LEVEL=debug environment variable should make Mono tell us in much more detail where it's looking for files!)

**Comment by Holraven** [comment]
Okay. First of all, the Mono stuff:

```
Mono JIT compiler version 4.2.2 (explicit/996df3c Wed Jan 20 00:19:48 EST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug 
    LLVM:          yes(3.6.0svn-mono-(detached/a173357)
    GC:            sgen
```

Which mono:
`/usr/local/bin/mono`

Then for the script:

```
Checking if Mono's in the PATH
/usr/local/bin/mono
Yes
Is Mono 32-bit?
    Architecture:  x86
Yes
Messing with libraries...
Downloading old SDL_image....
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53665  100 53665    0     0  30621      0  0:00:01  0:00:01 --:--:-- 30630
Copying stuff to /Library/Frameworks as administrator...

Should all be OK! Try launching via Steam. Any problems, log an issue on GitHub.
Press Return to close...
```

Debug is attached.
[SpaceChem-Debug.txt](https://github.com/leafi/fix-spacechem-os-x/files/129836/SpaceChem-Debug.txt)

**Comment by leafi** [comment]
Huh. Looks mostly good!

In your debug log you have:

`[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.`

Please follow the instructions on the main page for adding a steam_appid.txt file, then run manually with MONO_DEBUG=1 again.

(You need to be running mono from the Contents/Resources directory, and you need to add that steam_appid.txt file to said Contents/Resources folder.)

**Comment by Holraven** [comment]
steam_appid.txt was the key! Thanks for that! So I'm able to launch SpaceChem, but the mouse only moves when I'm clicking and holding the mouse button, which make it pretty useless...

Running it from Steam still brings the Zachtronics error message, in spite of changing the launcher as described...

**Comment by leafi** [comment]
Good! We're well on the way, then.  As you've said, fixing the launcher is key.

Since we know the right mono is /usr/local/bin/mono, we can delete the bit of the launcher that checks for Mono and type in the path manually.

In a text editor of your choice, open SpaceChem.app/Contents/MacOS/SpaceChem. It looks like a binary, but it's actually a Python file. `nano SpaceChem` from a Terminal in the right directory would work, or gvim or whatever.

From here follow the instructions on the front page about fixing the launcher the hard way. Basically deleting all the stuff that tries to find Mono (more detail in the guide!!!), then change the os.execlp() line near the end so that instead of os.execlp(which('mono'), ...   it looks like os.execlp('/usr/local/bin/mono', ...).

Oh btw - you say you've changed the launcher as described... The guide actually deletes the part of the launcher that opens up the Zachtronics web page, so check you're actually editing the right thing!

For reference of what it should sort of look like, take a look at "fixed-launcher.sh" in the Code part of this here GitHub. You'd need to use /usr/local/bin/mono not /Library/Frameworks/blbahblabhasbdlsbdhslbdsklbdasdfjskl/mono but yeah.

I think the main issue you've been experiencing is my script didn't do anything to the launcher because it saw a valid Mono available in $PATH, but the SpaceChem launcher script implements its own way of looking through $PATH for valid Mono and for some reason isn't finding the right one.

IIRC I remember reading that .app files actually get given a different $PATH variable on OS X El Capitan to what your real $PATH is. They get a kind of sanitized version, which wouldn't include /usr/local/bin. So we need to change your launcher manually in this case.

**Comment by Holraven** [comment]
> Delete the stuff that automatically searches for Mono (...)

I am such an idiot when it comes to reading instructions... I changed the last part, but forgot to remove the part where it checks for mono. All good now!

So I reckon the scripts needs to alter that bit as well..? Thanks anyhow! I can now continue my "chemical warfare"!  :+1:

**Comment by leafi** [comment]
Ya, script needs work! Glad to hear you're up and running though :)

**Comment by leafi** [comment]
I've updated the script to also munge the launcher if your Mono is at /usr/local/bin/mono.

**Comment by Holraven** [comment]
Way to go. And great work!
